version: "3.4"

services:
  zookeeper:
    image: "bitnami/zookeeper"
    restart: "always"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka"
    restart: "always"
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  mongodb:
    image: "mongo:latest"
    restart: "always"
    ports:
      - "27017:27017"
    volumes:
      - "mongo_db_data:/data/db"

  mysql:
    image: "mysql:latest"
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password


  adminer:
    image: "adminer:latest"
    restart: "always"
    ports:
      - "5000:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongo_db_data:
    driver: local
  mysql_data:
    driver: local

networks:
  default:
    external:
      name: order



